<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * @file
 * Primary module hooks for Mntrshp Module module.
 */
function mntrshp_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Add a condition to the query.
  if ($view->id() === 'matching_opportunities') {
    // Retrieve the logged-in user's job type term ID.
    $account = \Drupal::currentUser();
    $user = \Drupal\user\Entity\User::load($account->id());
    $user_job_type_values = $user->get('field_areas_of_interest')->getValue();
    $user_job_type_ids = array_column($user_job_type_values, 'target_id');
    // Apply the condition to filter jobs based on job type.
    $query->addWhere(0, 'node__field_job_type.field_job_type_target_id', $user_job_type_ids, 'IN');
    // dpm($query->where);
  }
}

function mntrshp_module_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_register_form') {
    // do something
  }
}
